title: "Formatura — Isadora Moreira de Borba"
description: "Convite de formatura em Design de Moda"
url: "http://formatura.isadoradeborba.des.br/"
lang: pt-BR

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
